# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8s Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'akstfsshkey.pub'
    

- task: TerraformInstaller@0
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resorce-manager-service-connection'
    backendAzureRmSubscriptionId: '2c5ae364-77f3-40a0-a3a5-bbb724cef2b0'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-storage-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'tfstatestorageaccountabc'
    backendAzureRmStorageAccountSku: 'Standard'
    backendAzureRmContainerName: 'terraform-state-file-container'
    backendAzureRmKey: 'dev-kubernetes.tfstate'
    allowTelemetryCollection: false'
       

- task: TerraformCLI@0
  displayName: Terraform apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resorce-manager-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: false
